### ISSUE TITLE
CI fails for a month

### ISSUE THREAD

**Issue by Patschke** [Menci/docker-archlinuxarm#6]
The last successful CI run that updates the images seems to be a month old. I guess as a result the images on docker get outdated?

Failing since then: https://github.com/Menci/docker-archlinuxarm/actions/runs/8167679102
Last sucessfull build: https://github.com/Menci/docker-archlinuxarm/actions/runs/8151787635

**Comment by ogarcia** [comment]
The truth is that I have also tried to get it to work ([here](https://github.com/ogarcia/docker-archlinux/tree/a4da21db0ad3b91b19e7d6bb77afab36190729b4)) but I don't know what happens to the GitHub runners that fail when using PGP. In the end I opted to take the repository to GitLab which works like a charm. If you are interested [it is here](https://gitlab.com/ogarcia/container-archlinux).

**Comment by Menci** [comment]
Fixed.

@ogarcia For the error if you're interested, that's because of [pacman uses `faccessat()`](https://gitlab.archlinux.org/pacman/pacman/-/commit/b4f11d5496a9f638278c8927f0c6032a332c75b5) while qemu-user doesn't implement `faccessat2` (until [this commit](https://gitlab.com/qemu-project/qemu/-/commit/35a2c85f7d691db7aa2c47181902ac87478eef7a#22a0a2b64d3ac6574f50e7997869293b275a1c5b_9148_9157)). Switching to glibc-based Debian works around this.

**Comment by ogarcia** [comment]
@Menci Thank you! The truth is that I would not have discovered the error in life. But the really curious thing is that in the GitLab runners it doesn't fail.

**Comment by yxing-xyz** [comment]
No need to switch to debian, just specify the version of qemu in the GitHub action
![image](https://github.com/user-attachments/assets/0e74cea6-49ef-4443-99b3-acd7489ca94d)

**Comment by ogarcia** [comment]
@yxing-xyz that explains the whole issue

**Comment by Menci** [comment]
@yxing-xyz I just don't know there's such an option and there IS pre-built newer version of qemu binfmt package... XD
